# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-24 22:28
from __future__ import unicode_literals

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_timestamp',
            field=models.DateTimeField(default='2000-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events', to='crm.Person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=address.models.AddressField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
