# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-10 23:46
from __future__ import unicode_literals

from django.db import migrations
import logging

log = logging.getLogger(__name__)

def rename_location_index(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        log.info("Postgres detected, renaming Event.location index.")
        schema_editor.execute(
            'ALTER INDEX events_event_location_id_2fb4171f rename TO events_event_legacy_location_id_2fb4171f'
        )
    else:
        log.info("Postgres not detected, skipping Event.location index rename.")

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180824_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='address',
        ),
        migrations.RunPython(rename_location_index, atomic=True)
    ]
