# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-10 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from geocodable.models import LocationAlias


class Migration(migrations.Migration):

    dependencies = [
        ('geocodable', '0001_initial'),
        ('events', '0003_auto_20190510_2346'),
    ]

    def migrate_to_locations(apps, schema_editor):
        Event = apps.get_model('events', 'Event')
        db_alias = schema_editor.connection.alias
        allEvents = Event.objects.using(db_alias).all()
        for event in allEvents:
            if event.address is not None:
                event.location_id = LocationAlias.objects.get_or_create(raw=event.address.raw)[0].id
                event.save()

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='geocodable.LocationAlias'),
        ),
        migrations.RunPython(migrate_to_locations),
    ]
