# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-10 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190510_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
    ]
