from django.conf import settings
from importlib import import_module
from import_export import widgets
from address.models import Address

class DatasetImporter(object):
    """Importing backend. Implement a subclass of this to add more importing
    backends. Must also include a Meta subclass that defines a ``resource``
    attribute, the value of which is an instantiated importing resource
    (PersonResource, EventResource, etc). Internally, Organizer uses
    django-import-export to manage creating/updating records generated by an
    importer backend."""
    def next(self):
        return self.next_page()

    def next_page(self):
        """The meat of your importer. Must return a ``tablib.Dataset`` for each
        page, and raise a StopIteration exception when out of pages."""
        raise NotImplementedError()

    def __iter__(self):
        self.init()
        return self

    def init(self):
        """Utility method to perform initial setup of the import"""
        pass

importerCache = None

def get_importer_class(name):
    global importerCache
    if importerCache is None:
        importerCache = collect_importers()
    return importerCache.get(name)

def collect_importers():
    ret = {}
    for app in settings.INSTALLED_APPS:
        try:
            imported = import_module('.'.join((app, 'importing')))
        except ImportError, e:
            continue
        if hasattr(imported, 'importers'):
            ret.update(imported.importers)
    return ret

class AddressWidget(widgets.Widget):
    def clean(self, value, row, *args, **kwargs):
        if value is None:
            return None
        ret = Address.objects.filter(raw=value).first()
        if ret is None:
            return Address.objects.create(raw=value)
        else:
            return ret

    def render(self, value, obj=None):
        if value is None:
            return None
        return value.raw
