from django.conf import settings
from django import forms
from . import plugins

class DatasetImporter(plugins.ConfigurablePlugin):
    """Importing backend. Implement a subclass of this to add more importing
    backends. Must also include a Meta subclass that defines a ``resource``
    attribute, the value of which is an instantiated importing resource
    (PersonResource, EventResource, etc). Internally, Organizer uses
    django-import-export to manage creating/updating records generated by an
    importer backend."""
    __metaclass__ = plugins.PluginMount
    app_module_name = 'importing'

    def __init__(self, configuration):
        self.configuration = configuration

    def next(self):
        return self.next_page()

    def next_page(self):
        """The meat of your importer. Must return a ``tablib.Dataset`` for each
        page, and raise a StopIteration exception when out of pages."""
        raise NotImplementedError()

    def __iter__(self):
        self.init()
        return self

    def init(self):
        """Utility method to perform initial setup of the import"""
        pass

    def options_form(self, *args, **kwargs):
        return forms.Form(*args, **kwargs)
