FROM ubuntu:20.04

RUN apt-get update && apt-get install -y python3 pipenv python3-pip && \
	ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /organizer

COPY ./Pipfile /organizer/

RUN pipenv lock -r > requirements.txt
RUN pip3 install -r requirements.txt

COPY . /organizer
