# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-30 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synctarget',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='synctarget',
            name='configuration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
