# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-31 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_auto_20190730_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='synctarget',
            name='lastRun',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
