# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-07 03:06
from __future__ import unicode_literals

from django.db import migrations
import organizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_auto_20190731_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsource',
            name='configuration',
            field=organizer.models.JSONField(blank=True, null=True),
        ),
    ]
