# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-07 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_auto_20190807_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportSink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('backend', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('configuration', models.TextField(blank=True, null=True)),
                ('lastRun', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='importsource',
            name='configuration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
