# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-15 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtering', '0001_initial'),
        ('sync', '0006_auto_20190807_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportsink',
            name='filter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='filtering.FilterNode'),
            preserve_default=False,
        ),
    ]
