# Generated by Django 3.2.3 on 2021-05-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocodable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
