# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0011_person_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('recurring', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='crm.Person')),
            ],
        ),
    ]
