# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='value',
            field=models.IntegerField(),
        ),
    ]
