# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-05 23:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0007_auto_20180805_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_on', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.PersonState')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Turf')),
            ],
        ),
    ]
