# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-29 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='neighborhood',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
