# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180802_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
