# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-07 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20180806_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='personstate',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
