# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-20 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20180807_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
