# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-11 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20180820_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
