# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 22:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations
from django.contrib.postgres.operations import CITextExtension
from django.db.models import Count
from django.db.models.functions import Lower
from crm.models import merge_models

def merge_emails(apps, schema_editor):
    Person = apps.get_model('crm', 'Person')
    db_alias = schema_editor.connection.alias
    duplicates = Person.objects.values(lower_email=Lower('email')) \
            .annotate(Count('id')) \
            .filter(id__count__gt=1)
    for dupe in duplicates.values_list('lower_email'):
        matches = Person.objects.filter(email__iexact=dupe).order_by('created')
        first = matches[0]
        duplicates = matches[1:]
        merged, relations = merge_models(first, *duplicates)
        with transaction.atomic():
            for d in duplicates:
                d.delete()
            first.save()
            for r in relations:
                r.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_person_phone'),
    ]

    operations = [
        migrations.RunPython(merge_emails, None),
        CITextExtension(),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(db_index=True, max_length=200, unique=True),
        ),
    ]
