# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-07 22:42
from __future__ import unicode_literals

from django.db import migrations, models

def copy_captain_flag(apps, schema_editor):
    Person = apps.get_model('crm', 'Person')
    TurfMembership = apps.get_model('crm', 'TurfMembership')

    for person in Person.objects.all():
        if TurfMembership.objects.filter(is_captain=True, person=person).exists():
            person.is_captain = True
            person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(copy_captain_flag),
    ]
