# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-22 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_person_phone'),
        ('geocodable', '0001_initial'),
    ]


    operations = [
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.ForeignKey(blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='geocodable.LocationAlias'),
        ),
    ]
