# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-22 23:55
from __future__ import unicode_literals

from django.db import migrations
from geocodable.models import LocationAlias, Location


class Migration(migrations.Migration):

    dependencies = [
        ('geocodable', '0001_initial'),
        ('crm', '0012_person_location'),
    ]
    def migrate_to_locations(apps, schema_editor):
        Person = apps.get_model('crm', 'Person')
        db_alias = schema_editor.connection.alias
        allPeople = Person.objects.using(db_alias).all()
        for person in allPeople:
            person.location_id = LocationAlias.objects.get_or_create(raw=person.address.raw)[0].id
            person.save()

    def migrate_from_locations(apps, schema_editor):
        Person = apps.get_model('crm', 'Person')
        db_alias = schema_editor.connection.alias
        allPeople = Person.objects.using(db_alias).all()
        for person in allPeople:
            if person.location.location is not None:
                person.address = person.location.location.fullName
                person.save()

    operations = [
        migrations.RunPython(migrate_to_locations, migrate_from_locations),
    ]
