# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-07 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0014_auto_20190507_2318'),
        ('crm', '0013_remove_turfmembership_is_captain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='turfmembership',
            name='person',
        ),
        migrations.RemoveField(
            model_name='turfmembership',
            name='turf',
        ),
        migrations.DeleteModel(
            name='Turf',
        ),
        migrations.DeleteModel(
            name='TurfMembership',
        ),
    ]
