# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-08 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20190507_2326'),
        ('crm', '0013_convert_to_geocodable'),
    ]

    operations = [
    ]
