# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-10 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_remove_person_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lng',
        ),
    ]
