# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0005_auto_20180802_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewNeighborNotificationTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_targets', to='crm.Turf')),
            ],
        ),
    ]
