# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newneighbornotificationtarget',
            name='last_notified',
            field=models.DateField(null=True),
        ),
    ]
