# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-05 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20180805_2335'),
        ('onboarding', '0002_newneighbornotificationtarget_last_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='newneighbornotificationtarget',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.PersonState'),
            preserve_default=False,
        ),
    ]
