# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-10 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20180807_0304'),
        ('onboarding', '0003_newneighbornotificationtarget_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newneighbornotificationtarget',
            name='state',
        ),
        migrations.AddField(
            model_name='newneighbornotificationtarget',
            name='states',
            field=models.ManyToManyField(to='crm.PersonState'),
        ),
    ]
