# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-10 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20180807_0304'),
        ('onboarding', '0004_auto_20180810_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newneighbornotificationtarget',
            name='turf',
        ),
        migrations.AddField(
            model_name='newneighbornotificationtarget',
            name='turfs',
            field=models.ManyToManyField(related_name='notification_targets', to='crm.Turf'),
        ),
    ]
