# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180824_2228'),
        ('onboarding', '0006_auto_20180814_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='newneighbornotificationtarget',
            name='turfs',
            field=models.ManyToManyField(related_name='notification_targets', to='crm.Turf'),
        ),
    ]
