# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_auto_20181016_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='deleted',
        ),
    ]
