# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_person_phone'),
        ('onboarding', '0008_remove_signup_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField()),
                ('handler', models.CharField(max_length=200)),
                ('configuration', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.OnboardingComponent')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Person')),
            ],
        ),
        migrations.AddField(
            model_name='signup',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
