# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_auto_20181021_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingstatus',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='onboarding.OnboardingComponent'),
        ),
    ]
