# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_auto_20181023_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingcomponent',
            name='configuration',
            field=models.TextField(blank=True, default=''),
        ),
    ]
