# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtering', '0001_initial'),
        ('onboarding', '0011_auto_20181023_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcomponent',
            name='filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='filtering.FilterNode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onboardingstatus',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onboardingstatus',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_statuses', to='crm.Person'),
        ),
    ]
