# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-07 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_auto_20190402_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newneighbornotificationtarget',
            name='states',
        ),
        migrations.RemoveField(
            model_name='newneighbornotificationtarget',
            name='turfs',
        ),
        migrations.DeleteModel(
            name='NewNeighborNotificationTarget',
        ),
    ]
