# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-16 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('configuration', models.TextField(blank=True, default='')),
                ('handler', models.CharField(choices=[('notifications.channels.Slack', 'Slack')], max_length=200)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='sources',
            field=models.ManyToManyField(to='notifications.NotificationSource'),
        ),
    ]
