# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-16 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationchannel',
            name='handler',
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='backend',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
