# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-16 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20190916_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
